services:
  - type: web
    name: university-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
